config/routes.rb
Helpr::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations" }
  
  devise_for :agents, :controllers => { :sessions => "agents/sessions", :registrations => "agents/registrations" }
  
  root :to => "home#home"
  
  devise_for :agents,  :path => "/", :path_names => { :sign_in => '/' }

  devise_for :admins,  :path => "/", :path_names => { :sign_in => '/', :sign_up => 'admins/registrations' }
  
  devise_for :customers

  resources :customers

  resources :chats

  resources :phrases

  match 'agents/join_chat' => 'agents#join_chat'
  
  match 'agents/view_all' => 'agents#view_all'
  
  resources :agents

  resources :admins

  resources :businesses

  match 'admins/graph' => 'admins#graph'

  match ':controller(/:action(/:id(.:format)))'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    
    # converts the time into a saveable format
    params[:business].parse_time_select! :start_hour
    params[:business].parse_time_select! :end_hour
    #creates a new business
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to new_admin_registration_path, notice: 'Business was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= simple_form_for @business, :html => { :class => 'form-horizontal' } do |f| %>
	<fieldset>
		<%= f.input :biz_name, :label => 'Business Name' %>
		<br>
		<%= f.input :biz_url, :label => 'Business URL', :as => :string %>
		<p>Users will visit this page to chat with agents.</p>
		<br>
		<h4>Set Availability of Agents</h4>
		<p>Round Up to Next 15 Minute Interval</p>
		<%= f.input :start_hour, :default => Time.now.change(:hour => 9, :min => 00), :combined => true, :minute_interval => 15, :time_separator => "" %>
		<%= f.input :end_hour, :default => Time.now.change(:hour => 17, :min => 00), :combined => true, :minute_interval => 15, :time_separator => "" %>
		<br>
		<%= f.submit :value => 'Create Business'%>
	</fieldset>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/new.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4">&nbsp;</div>
		<div class="span4">
			<h2>Add Your Business</h2>
			<%= render 'form' %>
			<%= link_to 'Back', businesses_path %>
		</div>
		<div class="span4">&nbsp;</div>
	</div>
</div>