config/routes.rb
Helpr::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations" }
  
  devise_for :agents, :controllers => { :sessions => "agents/sessions", :registrations => "agents/registrations" }
  
  root :to => "home#home"
  
  devise_for :agents,  :path => "/", :path_names => { :sign_in => '/' }

  devise_for :admins,  :path => "/", :path_names => { :sign_in => '/', :sign_up => 'admins/registrations' }
  
  devise_for :customers

  resources :customers

  resources :chats

  resources :phrases

  match 'agents/join_chat' => 'agents#join_chat'
  
  match 'agents/view_all' => 'agents#view_all'
  
  resources :agents

  resources :admins

  resources :businesses

  match 'admins/graph' => 'admins#graph'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
    # Relationships
  belongs_to :business
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :phone, :business_attributes
  
  accepts_nested_attributes_for :business
  
  
  # Callbacks
  before_save :reformat_phone
  
  
  # Validations`
  validates_presence_of :first_name, :last_name
  validates_format_of :phone, :with => /^\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}$/, :message => "should be 10 digits (area code needed) and delimited with dashes only"
  
  # Scopes
  
  # Other Methods
  
   def name
      "#{last_name}, #{first_name}"
   end
   
   # Callback method 
   private
   def reformat_phone
     phone = self.phone.to_s  # change to string in case input as all numbers 
     phone.gsub!(/[^0-9]/,"") # strip all non-digits
     self.phone = phone       # reset self.phone to new string
   end
   
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :business_id, :first_name, :last_name
  belongs_to :business
  
  
  # Scopes
  scope :alphabetical, order('last_name, first_name')
  scope :for_business, lambda {|business_id| where("business_id = ?", business_id) }
  
end

app/models/business.rb
class Business < ActiveRecord::Base
  
  # removed admin_id
  attr_accessible :biz_name, :biz_url, :end_hour, :start_hour 
  # Callbacks

  # Relationships
  has_many :agents, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :phrases, dependent: :destroy

  has_one :admin, dependent: :destroy

  has_many :customers, through: :chats
  
  accepts_nested_attributes_for :admin

  # Validations
  validates_presence_of :biz_name, :biz_url
  validates_time :end_hour, :after => :start_hour, :after_message => 'must be after start hour.'
  validates_uniqueness_of :biz_url
   
    
  # Scopes
  
  # Other Methods

  
end

app/models/chat.rb
class Chat < ActiveRecord::Base

  belongs_to :business
  belongs_to :customer

  has_many :messages
  
  attr_accessible :business_id, :chat, :customer_id, :channel
   
  accepts_nested_attributes_for :customer

end

app/models/chat_user.rb
class ChatUser < ActiveRecord::Base

  def self.user(session, name=nil)

    if session[:user_id] == nil
      user = self.new
      user.first_name = name.to_s
      if user.save
        session[:user_id] = user.id
      end
    else
      user = self.find(session[:user_id])
    end

    # Return the user
    user

  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :chats

  has_many :businesses, through: :chats
  
  attr_accessible :first_name, :last_name, :phone, :email, :chats_attributes
  
  
  

end

app/models/message.rb
class Message < ActiveRecord::Base

  attr_accessible :shared_file

  belongs_to :chat
  has_one :business, :through => :chat

  has_attached_file :shared_file,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml"

  # Scope
   scope :for_chat, lambda {|chat_id| where("chat_id = ?", chat_id) }
   scope :order_by_time, order('created_at')
   scope :for_business, lambda {|business_id| joins(:business).where("business_id = ?", business_id) }

  
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  attr_accessible :business_id, :phrase

  belongs_to :business
  
  #Scopes
  scope :for_business, lambda {|business_id| where("business_id = ?", business_id) }
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  protect_from_forgery :except => :authenticate # stop rails CSRF protection for this action

  def post_message
    chat = Chat.find(params[:chat_id])
    message = Message.new
    message.chat_id = chat.id

    user = ChatUser.user(session)
    message.user_id = user.id
    
    # escapes &, <, > in rails
    message.message = CGI::escapeHTML(params[:message])

    payload = message.attributes
    payload[:user] = user.attributes

    if message.save
      Pusher["presence-" + chat.channel].trigger('send_message', payload)
      render :text => "sent"
    else
      render :text => "failed"
    end
  end

  def authenticate
    if params[:user_id]
      user = ChatUser.find(params[:user_id])
      auth = Pusher[params[:channel_name]].authenticate(params[:socket_id],
                                                        :user_id => user.id,
                                                        :chat_user => user.attributes
      )
      render :json => auth
    else
      render :text => "Not authorized", :status => '403'
    end
  end

  def upload_file
    chat = Chat.find(params[:chat_id])
    message = Message.create(params[:message])
    message.chat_id = chat.id

    user = ChatUser.user(session)
    message.user_id = user.id
    download_url = message.shared_file.url(:download => true)
    file_name = message.shared_file_file_name
    message.message = "<a href=\""+download_url+"\" target='_blank'>"+file_name+"</a>"

    payload = message.attributes
    payload[:user] = user.attributes

    if message.save
      Pusher["presence-" + chat.channel].trigger('send_message', payload)

      render :text => "file uploaded"
    else
      render :text => "upload failed"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home2

  end
end

app/helpers/admins_helper.rb
module AdminsHelper
   def resource_name
    :admin
  end

  def resource
    @resource ||= Admin.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:admin]
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
  def resource_name
    :agent
  end

  def resource
    @resource ||= Agent.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:agent]
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <p style="color: red;">#{sentence}</p>
      <ul style="color:black;">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/admins/_form.html.erb
<%= simple_form_for(@admin) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/shared/_links.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_admin_password_path %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_admin_confirmation_path %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_admin_unlock_path %><br />
<% end -%>

app/views/admins/show.html.erb
<h1 style='text-align: center;'><%= @admin.business.biz_name %></h1>

<div class="container">

  <div class="well">
    <div class="row">

      <div class="span4">
        <h3>Welcome, <u><%= @admin.first_name %> <%= @admin.last_name %></u></h3>
        <p>Edit information about <b><%= @business.biz_name %></b> on this page.</p>
        <%= link_to(edit_admin_registration_path) do %>
            <button class="btn btn-info">
              <span class="white-text">Edit Info</span>
            </button>
        <% end %>
        &nbsp;
        <!-- sign out button -->
        <%= link_to(destroy_admin_session_path, :method => :delete) do %>
            <button class="btn btn-danger">
              <span class="white-text">Sign Out</span>
            </button>
        <% end %>
      </div>

      <div class="span1">&nbsp;</div>

      <div class="span3">
        <br>
        <h4>Admin Info</h4>
        <p><b>Email:</b> <%= @admin.email %></p>
        <p><b>Phone:</b> <%= number_to_phone @admin.phone %></p>
      </div>
      <div class="span3">
        <br>
        <h4>Business Info</h4>
        <p><b>Name:</b> <%= @business.biz_name %></p>
        <p><b>Hours:</b> <%= @business.start_hour.strftime("%I:%M %p")%> - <%= @business.end_hour.strftime("%I:%M %p") %></p>
      </div>

    </div>
  </div>

  <div class="row main-features">
    <div class="span4">
      <div class="well" style="height:200px;">
        <h3>Customer Chat Link</h3>
        <p>Give this link to your customers so they can chat with your agents.</p> <br>
        <div  style="font-size:12px; text-align: center;">
          <%= link_to @link, @link %>
        </div>
      </div>
    </div>

    <div class="span4">
      
      <% if @agents.size > 0 %>
      
      <div class="well" style="height:200px;">
        <h3>Organize Agents</h3>
        <p>Here you can manage the agents who chat with customers for your business.</p> <br>
        <div  style="text-align: center;">
          <%= link_to(new_agent_registration_path) do %>
              <button class="btn btn-info">
                <span class="white-text">Add</span>
              </button>
          <% end %> &nbsp;
          <%= link_to(agents_view_all_path) do %>
              <button class="btn btn-info">
                <span class="white-text">View All</span>
              </button>
          <% end %>
        </div>
      </div>
      
      <% else %>
      
      <div class="well" style="height:200px; background-color: #FFFF99; color: black;">
        <h3>Organize Agents</h3>
        <p>Here you can manage the agents who chat with customers for your business.</p> <br>
        <div  style="text-align: center;">
 		  <p>You have not created any agents for your business.  Add agents now.</p>
          <%= link_to(new_agent_registration_path) do %>
              <button class="btn btn-info">
                <span class="white-text">Add</span>
              </button>
          <% end %> &nbsp;
        </div>
      </div>
      
      <% end %>
    </div>

    <div class="span4">
    		
    <% if @phrases.size > 0 %>
    	
      <div class="well" style="height:200px;">
        <h3>Manage Phrases</h3>
        <p>Phrases are a fast and easy way for agents to respond to customers.</p> <br>
        <div  style="text-align: center;">
          <%= link_to(new_phrase_path) do %>
              <button class="btn btn-info">
                <span class="white-text">Add</span>
              </button>
          <% end %> &nbsp;
          <%= link_to(phrases_path) do %>
              <button class="btn btn-info" >
                <span class="white-text">View All</span>
              </button>
          <% end %>
        </div>
      </div>
      
      <% else %>
      
      <div class="well" style="height:200px; background-color: #FFFF99; color: black;">
        <h3>Manage Phrases</h3>
        <p>Phrases are a fast and easy way for agents to respond to customers.</p> <br>
        <div  style="text-align: center;">
        <p>You have not created any phrases for your business.  Add phrases now.</p>
          <%= link_to(new_phrase_path) do %>
              <button class="btn btn-info">
                <span class="white-text">Add</span>
              </button>
          <% end %> &nbsp;
        </div>
      </div>
      
      <% end %>
    </div>

    <div class="span6">

      <h3>Word Cloud</h3>
      <p><b>What are customers chatting about?</b></p> <br>
      <button class="btn btn-info" onclick="javascript: $('#reveal_word_cloud').trigger('click');">Show Word Cloud</button>
      <h3><a id="reveal_word_cloud" href="#" data-reveal-id="word_cloud_modal"></a>
        <br>
      </h3>
      <div id="word_cloud_modal" class="reveal-modal" style="text-align: center;">
        <h3>Word Cloud</h3>
        <p style="color: #000000;"><b>What are customers chatting about?</b></p> <br>
        <% if !@messages_array.empty? %>
        	<img src="<%= @data.body['url'] %>"
            	height="<%= @data.body['height'] %>"
             	width="<%= @data.body['width'] %>" >
        <% else %>
        	<p style="color: #000000;">No one has chatted with your business yet.</p>
        <% end %>
             
        <a class="close-reveal-modal">&#215;</a>
      </div>

    </div>

    <div class="span6">
      <h3>Chat Service Statistics</h3>
      <p><b>What hour of the day do your customers chat the most?</b></p> <br>
      <button class="btn btn-info" onclick="drawVisualization(<%= @business.id %>)">Show Statistics</button>
      <h3><a href="#" id="reveal_graph" data-reveal-id="graph_modal"></a>
        <br>
      </h3>
      <div id="graph_modal" class="reveal-modal" style="text-align: center;">
        <h3>Chat Service Statistics</h3>
        <p  style="color: #000000;"><b>What hour of the day do your customers chat the most?</b></p> <br>
        <div id="graph"></div>
        <a class="close-reveal-modal">&#215;</a>
      </div>

    </div>

  </div>

</div>

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load('visualization', '1', {packages: ['corechart']});

</script>

<script src="https://app.divshot.com/js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpr</title>

  <meta http-equiv="Cache-Control" content="private, no-store, max-age=0, no-cache, must-revalidate, post-check=0, pre-check=0">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="Fri, 01 Jan 1990 00:00:00 GMT">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" charset="utf-8">
      var PUSHER_KEY = '<%= Pusher.key %>'
  </script>

  <!--divshot-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <link rel="stylesheet" href="https://app.divshot.com/css/divshot-util.css">

  <link rel="stylesheet" href="https://app.divshot.com/themes/superhero/bootstrap.min.css">

  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36413065-1']);
      _gaq.push(['_setDomainName', 'herokuapp.com']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  </script>

</head>
<body>
<% if notice != nil %>
	<p class="alert" style='text-align: center;'><b><%= notice %></b></p>
<% end %>
<% if alert != nil %>
	<p class="alert" style='text-align: center;'><b><%= alert %></b></p>
<% end %>

<%= yield %>

<div id="footer">
  <br/>
  <p>&copy; 2012 <a href="http://livehelpr.herokuapp.com/" target="_blank">Helpr</a> by <b>Mike Ferraco</b> and <b>Omkar Ambardekar</b>, Carnegie Mellon University</p>
  <p>Pusher Chat is proudly powered by <a href="http://pusherapp.com/" target="_blank">Pusher App</a>. Created by <a href="http://tarnfeld.com/" target="_blank">Tom Arnfeld</a>.</p>
</div>


<script type="text/javascript">
    var uvOptions = {};
    (function() {
        var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
        uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/fUiRSJkFCIMvCrBWNJLw.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
    })();
</script>

<!--
<script src="http://cdn.wibiya.com/Toolbars/dir_1295/Toolbar_1295647/Loader_1295647.js" type="text/javascript"></script>
<noscript>
  <a href="http://www.wibiya.com/">Web Toolbar by Wibiya</a>
</noscript>
-->

</body>
</html>

app/views/partials/_admin_sign_in.erb
<div class="well">
<h3>Admin</h3>
<%= form_for("admin", :url => admin_session_path) do |f| %>
  <div><%= f.label :email %>
  <%= f.email_field :email %></div>

  <div><%= f.label :password %>
  <%= f.password_field :password %></div>

  <div><%= f.submit "Sign in", :class => 'btn btn-primary' %></div>

<% end %>

</div>

app/views/partials/_agent_sign_in.erb
<div class="well">
<h3>Agent</h3>
<%= form_for("agent", :url => agent_session_path) do |f| %>
  <div><%= f.label :email %>
  <%= f.email_field :email %></div>

  <div><%= f.label :password %>
  <%= f.password_field :password %></div>

  <div><%= f.submit "Sign in", :class => 'btn btn-primary' %></div>
  

<% end %>

</div>