config/routes.rb
Helpr::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations" }
  
  devise_for :agents, :controllers => { :sessions => "agents/sessions", :registrations => "agents/registrations" }
  
  root :to => "home#home"
  
  devise_for :agents,  :path => "/", :path_names => { :sign_in => '/' }

  devise_for :admins,  :path => "/", :path_names => { :sign_in => '/', :sign_up => 'admins/registrations' }
  
  devise_for :customers

  resources :customers

  resources :chats

  resources :phrases

  match 'agents/join_chat' => 'agents#join_chat'
  
  match 'agents/view_all' => 'agents#view_all'
  
  resources :agents

  resources :admins

  resources :businesses

  match 'admins/graph' => 'admins#graph'

  match ':controller(/:action(/:id(.:format)))'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home2

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.erb
<div class="container-fluid">
  <br>
  <br>
  <!-- logins for admin and agent -->

  <div class="row-fluid">
    <div class="span1" >&nbsp;</div>
    <div class="span3">
      <!-- admin sign in -->
      <%= render "partials/admin_sign_in" %>
    </div>
    <div class="span4" >
      <div style="text-align: center; "><%= image_tag 'helpr-landing-page.png', :size => '500x500' %>
      </div>
      <br>
      <div class="row-fluid">
        <div class="span4">
          <div class="row-fluid">
            <span class="span8">
          <%= image_tag 'logo.png', :size => '200x200' %>
              </span>
            <span class="span4">
              <%= image_tag 'beta-bookmark.png', :size => '50x40', :class => "tiptip", :title => "This is a beta version"%>
              </span>
          </div>
        </div>
        <div class="span8">
          for the best small business customer service application on the web.
        </div>
      </div>
      <br>
      <div style="text-align: center;">
        <%= link_to(new_admin_registration_path) do %>
            <button class="btn btn-primary btn-large">
              <span> Sign Up Today!</span>
            </button>
        <% end %>
      </div>
    </div>
    <div class="span3">
      <!-- agent sign in -->
      <%= render "partials/agent_sign_in" %>
    </div>
    <div class="span1">&nbsp;</div>
  </div>

</div>