config/routes.rb
Helpr::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations" }
  
  devise_for :agents, :controllers => { :sessions => "agents/sessions", :registrations => "agents/registrations" }
  
  root :to => "home#home"
  
  devise_for :agents,  :path => "/", :path_names => { :sign_in => '/' }

  devise_for :admins,  :path => "/", :path_names => { :sign_in => '/', :sign_up => 'admins/registrations' }
  
  devise_for :customers

  resources :customers

  resources :chats

  resources :phrases

  match 'agents/join_chat' => 'agents#join_chat'
  
  match 'agents/view_all' => 'agents#view_all'
  
  resources :agents

  resources :admins

  resources :businesses

  match 'admins/graph' => 'admins#graph'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :chats

  has_many :businesses, through: :chats
  
  attr_accessible :first_name, :last_name, :phone, :email, :chats_attributes
  
  
  

end

app/controllers/customers_controller.rb
require "router/agent_router"

class CustomersController < ApplicationController
  def new
    @customer = Customer.new
    business_param = params[:business]
    if business_param!= nil
      @business = Business.find_by_biz_url(business_param)
      time = Time.new
      #if (time.hour.to_i+1).between?(@business.start_hour.hour, @business.end_hour.hour)
        @available = true
      #else
        #show unavailability
        #@availability = "We are not available at this time! You can contact us between: "+@business.start_hour.strftime("%I:%M%p").to_s+" & "+@business.end_hour.strftime("%I:%M%p").to_s
      #end

      #TODO redirect to a custom error page instead of employee login page
      if @business == nil
        redirect_to "/"
      end
    else
      redirect_to "/"
    end
  end

  def index

    #find if customer already exists or else create new entry
    input_customer_email = params[:customer][:email]
    existing_customer = Customer.find_by_email(input_customer_email)
    if input_customer_email != nil && existing_customer != nil
      @customer = existing_customer
    else
      @customer = Customer.new
      @customer.first_name = params[:customer][:first_name]
      @customer.last_name = params[:customer][:first_name]
      @customer.email = params[:customer][:email]
      @customer.phone = params[:customer][:phone]
    end
    @customer.save
   

    #create a new chat instance
    @chat = Chat.new
    @chat.business_id = params[:customer][:chat][:business_id]
    @chat.customer_id = @customer.id
    @chat.save
    @chat.channel = "message_channel_" + @chat.id.to_s
    @chat.save

    #find user in session or create new user in session
    @user = ChatUser.user(session, @customer.first_name)
    #retrieve any existing messages sent to the chat room
    @messages = Message.all(:conditions => ["chat_id = ?", @chat.id.to_s])

    #retrieve the business association of this chat
    @business = @chat.business

    #select an agent of this business and route the chat to that agent
    agent_id = AgentRouter.select_agent(@business)

    #notify agents of incoming chat
    channel_name = "cc-new-chat-channel-"+agent_id.to_s
    event_name = "customer-call-event"
    Pusher[channel_name].trigger(event_name, {:chat_id => @chat.id.to_s, :customer_name => @chat.customer.first_name, :customer_id => @chat.customer.id})

  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<%= javascript_include_tag "http://js.pusherapp.com/1.9/pusher.min.js" %>


<script type="text/javascript">
    // Set the globals used by chat.js
    channel = "<%= @chat.channel %>";
    chat_id = "<%= @chat.id %>";
    user_id = "<%= @user.id %>";

</script>


<div class="container">
  <div class="page-header">
    <h1>Welcome to <%= @business.biz_name  %></h1>
  </div>
  <!--<div class="alert alert-info hidden-phone">
    <a class="close" data-dismiss="alert">×</a>
        <span>
          <b>Ready to dive in?</b>&nbsp;Click the page name dropdown in the top left
          and create a new page using the embedded form.</span>
  </div>-->
  <div class="well" id="chat_interface" name="chat_interface" style='text-align:center;'>

    <!--pusher chat stub-->
    <div id="wrapper">
      <div>
        <h2 style="text-align: center;"><%= @business.biz_name %></h2>
        <span id="loading"></span>
      </div>
      <ul id="messages" style='text-align: left; color: black;'>
        <% @messages.each do |message| %>
            <% user = ChatUser.find(message.user_id) %>
            <li<% if user.id == @user.id %> class="you"<% end %>><strong><%= user.first_name %></strong> said:<br><%= auto_link_urls(message.message, { :target => "_blank" }) %></li>
        <% end %>
      </ul>
      <div id="message-overlay"></div>
      <textarea disabled="disabled" id="message" name="message">Type your message here and hit enter...</textarea>
    </div>
    <!--pusher chat stub-->

    <!--dropbox-->


        <%= form_for Message.new, :remote => true, :url => { :controller => "api", :action => "upload_file" }, :html => { :id => "fileUploadForm", :target => "results" }  do |f| %>

            <div class="controls">
              <%= f.submit "Upload File", :class => "btn btn-primary" %>
              <%= f.file_field :shared_file %>

            </div>
            <input type="hidden" id="chat_id" name="chat_id" value="<%= @chat.id %>" />

        <% end %>


        <a class="btn btn-small btn-danger" href="javascript:endChat('<%= @user.first_name %>', 'customer')"><span class="btn-label">End Chat</span></a>


    <div id="upload_status"></div>

    <iframe src="/assets/uploader.js" width="0" id="results" name="results" height="0" border="0" frameborder="0" scrolling="auto" align="center" hspace="0" vspace=""></iframe>

  </div>

  <!--<p class="text-info lead">While using Divshot, your changes are automatically saved to the server
as you make them so you never have to worry about losing your work.</p>-->

</div>

<script src="https://app.divshot.com/js/bootstrap.min.js"></script>

app/views/customers/new.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <span class="brand">Helpr</span>
      <div class="navbar-content">
        <ul class="nav "></ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="span3">
    <div class="well">
      <h1>Welcome to <%= @business.biz_name %>!</h1>
    </div>
  </div>

  <% if @available %>
  <div class="row">
    <div class="span3"></div>
    <div class="span6">
      <div class="well">
        <div class="well">
          <h4>We just need a few details about you and then we are ready to go!</h4>
          <%= simple_nested_form_for @customer, :url => '/customers/index' do |f| %>
			
			<%= f.input :first_name, :required => true %>
			<%= f.input :last_name, :required => true %>
			<%= f.input :email, :required => true %>
			<%= f.input :phone, :required => true %>
					
			<%= f.simple_fields_for :chat do |chat| %>
				<%= chat.input :business_id, :as => :hidden, :input_html => { :value => @business.id }%>
			<% end %>
				
				<br>
				
			<%= f.submit "Start Chat", :class => 'btn btn-success'%> <br><br>
			<% end %>
        </div>
      </div>
    </div>
    <div class="span3"></div>
  </div>

  <% else %>

      <div class="well">
           <%= @availability.to_s %>
      </div>

  <% end %>

</div>
<script src="https://app.divshot.com/js/bootstrap.min.js"></script>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @customer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @customer.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>